# Generated by Django 3.2.25 on 2024-05-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='Sumo',
        ),
    ]
